/**
 * The values the extension MIRRORS from the daemon — never a second, separate setting that could drift from it (the owner,
 * 2026-10-05). Since daemon #17 (E7.S2c) `status --json` answers them as `limits`, and `contracts/status-limits.json`
 * names each field with its range and default (generated by the daemon's `ContractFilesTests`). `LIMIT_FIELDS` below is
 * the compiled copy of that contract — the bundle reads no repository file at run time — held EQUAL to it by
 * `daemonLimits.test.ts`. A status without `limits` (a daemon before #17), or a field that is not a whole number inside its
 * range, reads as that field's contract default: the daemon's value wins whenever it gives one.
 */

export interface DaemonLimits {
  /** `runs.historyRetentionDays`: the days of history the daemon keeps. */
  readonly historyRetentionDays: number;
  /** `requests.futureSkewSeconds`: how far ahead a request's stamp may lie. */
  readonly futureSkewMs: number;
  /** `requests.graceSeconds`: how long a request waits before the sweep may call it stale. */
  readonly requestGraceMs: number;
  /** `act.maxShownNames`: the longest shown list an A4 preview carries. */
  readonly maxShownNames: number;
  /** `systemd.unitStopTimeoutSeconds`: `systemctl stop`'s ceiling. */
  readonly unitStopSeconds: number;
  /** `commands.drainGraceMilliseconds`: the drain after a killed command, waited twice. */
  readonly drainGraceMs: number;
}

/** One field of `contracts/status-limits.json`, as this build knows it. */
interface LimitField {
  readonly name: string;
  readonly min: number;
  readonly max: number;
  readonly default: number;
  /** Where the field lands, and the factor from its unit to the reader's. */
  readonly into: keyof DaemonLimits;
  readonly scale: number;
}

export const LIMIT_FIELDS: readonly LimitField[] = [
  { name: 'historyRetentionDays', min: 7, max: 366, default: 90, into: 'historyRetentionDays', scale: 1 },
  { name: 'requestFutureSkewSeconds', min: 60, max: 3600, default: 300, into: 'futureSkewMs', scale: 1000 },
  { name: 'requestGraceSeconds', min: 60, max: 600, default: 60, into: 'requestGraceMs', scale: 1000 },
  { name: 'maxShownNames', min: 1, max: 10_000, default: 10_000, into: 'maxShownNames', scale: 1 },
  { name: 'unitStopSeconds', min: 120, max: 600, default: 120, into: 'unitStopSeconds', scale: 1 },
  { name: 'drainGraceMilliseconds', min: 500, max: 10_000, default: 2000, into: 'drainGraceMs', scale: 1 },
];

type Fields = Readonly<Record<string, unknown>>;

function isFields(value: unknown): value is Fields {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function limitsBlock(body: unknown): Fields {
  const limits = isFields(body) ? body.limits : undefined;

  return isFields(limits) ? limits : {};
}

/** The field's value when it is a whole number inside its range, else its default — in the reader's unit. */
function isIn(field: LimitField, value: unknown): value is number {
  return Number.isInteger(value) && (value as number) >= field.min && (value as number) <= field.max;
}

function valueOf(field: LimitField, value: unknown): number {
  return (isIn(field, value) ? value : field.default) * field.scale;
}

/** The daemon's limits from a `status` body, field by field. */
export function daemonLimitsOf(body: unknown): DaemonLimits {
  const limits = limitsBlock(body);

  return Object.fromEntries(LIMIT_FIELDS.map((field) => [field.into, valueOf(field, limits[field.name])])) as unknown as DaemonLimits;
}

/** Every field its contract default — what a daemon before #17 keeps and allows. */
export const FALLBACK_LIMITS: DaemonLimits = daemonLimitsOf(undefined);
